import json

# 为咨询场景定制的 notebook，包含降噪选项
nb = {
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {
  "accelerator": "GPU",
  "colab": {"gpuType": "T4", "provenance": []},
  "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
  "language_info": {"name": "python", "version": "3.10.0"}
 },
 "cells": [
  # ── Title ─────────────────────────────────────────
  {
   "cell_type": "markdown", "id": "title-cell", "metadata": {},
   "source": [
    "# Audio to Text - faster-whisper + Free GPU (咨询场景优化版)\n",
    "\n",
    "> Model: faster-whisper large-v3 / turbo  \n",
    "> Platform: Google Colab (T4) or AWS Studio Lab\n",
    "\n",
    "**适合：用户访谈、咨询对话、多人反馈会议**\n",
    "\n",
    "| Step | 内容 | 是否必选 |\n",
    "|------|------|----------|\n",
    "| 0 | 检查 GPU | 必选 |\n",
    "| 1 | 安装依赖 | 必选 |\n",
    "| 2 | 挂载 Google Drive | 必选 |\n",
    "| 3 | 配置参数 | 必选 |\n",
    "| **3.5** | **降噪预处理（可选）** | **按需启用** |\n",
    "| 4 | 加载模型 & 转录 | 必选 |\n",
    "| 5 | 保存输出（txt + srt）| 必选 |\n",
    "| 6 | WhisperX 说话人分离 | **必选** |\n",
    "| 7 | AI 优化处理（咨询场景） | **必选** |\n",
    "\n",
    "---\n"
   ]
  },
  # ── Step 0 ────────────────────────────────────────
  {
   "cell_type": "markdown", "id": "step0", "metadata": {},
   "source": [
    "## Step 0 - Check GPU\n",
    "\n",
    "Colab: Runtime -> Change runtime type -> **GPU (T4)**  \n",
    "Studio Lab: Start with **GPU** option\n"
   ]
  },
  {
   "cell_type": "code", "execution_count": None, "id": "check-gpu", "metadata": {}, "outputs": [],
   "source": [
    "import subprocess\n",
    "r = subprocess.run(['nvidia-smi', '--query-gpu=name,memory.total,memory.free', '--format=csv,noheader'], capture_output=True, text=True)\n",
    "if r.returncode == 0:\n",
    "    print('GPU available:', r.stdout.strip())\n",
    "else:\n",
    "    print('No GPU detected. Please switch runtime to GPU and re-run.')\n"
   ]
  },
  # ── Step 1 ────────────────────────────────────────
  {
   "cell_type": "markdown", "id": "step1", "metadata": {},
   "source": ["## Step 1 - Install\n"]
  },
  {
   "cell_type": "code", "execution_count": None, "id": "install", "metadata": {}, "outputs": [],
   "source": [
    "# faster-whisper does NOT require system ffmpeg\n",
    "# Uncomment next line if your audio is .m4a / .aac\n",
    "# !apt-get install -y -q ffmpeg\n",
    "!pip install -q faster-whisper\n"
   ]
  },
  # ── Step 2 ────────────────────────────────────────
  {
   "cell_type": "markdown", "id": "step2", "metadata": {},
   "source": [
    "## Step 2 - Mount Google Drive\n",
    "\n",
    "Put your audio file in Google Drive root, then mount here.\n"
   ]
  },
  {
   "cell_type": "code", "execution_count": None, "id": "mount-drive", "metadata": {}, "outputs": [],
   "source": [
    "from google.colab import drive\n",
    "drive.mount('/content/drive')\n",
    "\n",
    "import os\n",
    "DRIVE_ROOT = '/content/drive/MyDrive'\n",
    "print('Drive root contents:')\n",
    "for f in sorted(os.listdir(DRIVE_ROOT))[:20]:\n",
    "    print(' ', f)\n"
   ]
  },
  # ── Step 3: 配置（咨询场景专用）───────────────────────
  {
   "cell_type": "markdown", "id": "step3", "metadata": {},
   "source": [
    "## Step 3 - Config (咨询场景优化)\n",
    "\n",
    "| Param | Default | Notes |\n",
    "|-------|---------|-------|\n",
    "| AUDIO_FILE | 见下文 | 请改为你的音频文件名 |\n",
    "| MODEL_SIZE | large-v3 | 优先准确率 |\n",
    "| LANGUAGE | zh | 中文对话 |\n",
    "| BATCH_SIZE | 16 | T4 稳定值 |\n",
    "| VAD_FILTER | True | 跳过静默，提高效率 |\n",
    "| WORD_TIMESTAMPS | True | 词级时间戳用于说话人分离 |\n"
   ]
  },
  {
   "cell_type": "code", "execution_count": None, "id": "config", "metadata": {}, "outputs": [],
   "source": [
    "# ====== 咨询场景配置 ======\n",
    "# 请确保此音频文件已在 Google Drive 根目录\n",
    "AUDIO_FILE = \"03-26_咨询：智能眼镜“乐奇”用户体验反馈.mp3\"  # 改为你的音频文件名\n",
    "AUDIO_PATH  = f'/content/drive/MyDrive/{AUDIO_FILE}'\n",
    "OUTPUT_PATH = '/content/drive/MyDrive/transcript.txt'\n",
    "SRT_PATH    = '/content/drive/MyDrive/transcript.srt'\n",
    "\n",
    "MODEL_SIZE      = 'large-v3'  # tiny/base/small/medium/turbo/large-v3\n",
    "LANGUAGE        = 'zh'         # zh/en/ja or None for auto\n",
    "BATCH_SIZE      = 16\n",
    "VAD_FILTER      = True\n",
    "WORD_TIMESTAMPS = True\n",
    "# ========================\n",
    "\n",
    "import os\n",
    "assert os.path.exists(AUDIO_PATH), f'文件未找到: {AUDIO_PATH}'\\\n",
    "    '\\n请确认音频文件已上传至 Google Drive 根目录，并修改 AUDIO_FILE 变量。'\n",
    "size_mb = os.path.getsize(AUDIO_PATH)/1024/1024\n",
    "print(f'音频文件: {AUDIO_FILE} ({size_mb:.1f} MB)')\n"
   ]
  },
  # ── Step 3.5: 降噪预处理（可选）─────────────────────────
  {
   "cell_type": "markdown", "id": "step3.5", "metadata": {},
   "source": [
    "## Step 3.5 — 降噪预处理（可选）\n",
    "\n",
    "**适用场景**：音频含环境噪音（键盘声、空调声、翻纸声等）\n",
    "\n",
    "**降噪算法**：Spectral Gating (noisereduce)  \n",
    "**效果**：提高语音清晰度，改善说话人分离精度\n",
    "\n",
    "**注意**：对干净录音无需启用，可能轻微影响音质。"
   ]
  },
  {
   "cell_type": "code", "execution_count": None, "id": "denoise", "metadata": {}, "outputs": [],
   "source": [
    "# =========== 降噪配置 ===========\n",
    "ENABLE_DENOISE = True  # True=启用降噪，False=跳过\n",
    "DENOISED_PATH  = '/content/drive/MyDrive/audio_denoised.wav'  # 降噪后音频\n",
    "# ===============================\n",
    "\n",
    "if ENABLE_DENOISE:\n",
    "    print(\"安装 noisereduce...\")\n",
    "    !pip install -q noisereduce\n",
    "    \n",
    "    import numpy as np\n",
    "    import soundfile as sf\n",
    "    import librosa\n",
    "    import noisereduce as nr\n",
    "    import time\n",
    "    \n",
    "    print(f\"加载音频: {AUDIO_PATH}\")\n",
    "    t0 = time.time()\n",
    "    y, sr = librosa.load(AUDIO_PATH, sr=None, mono=True)\n",
    "    print(f\"  采样率: {sr} Hz, 时长: {len(y)/sr:.1f}s\")\n",
    "    \n",
    "    # 估计噪音区域（开头/结尾的静默段）\n",
    "    noise_samples = min(int(sr * 1.0), len(y) // 10)  # 取前1秒或总长的10%\n",
    "    noise_clip = y[:noise_samples]\n",
    "    \n",
    "    print(\"降噪处理中...\")\n",
    "    # Spectral gating (noisereduce)\n",
    "    y_denoised = nr.reduce_noise(y=y, sr=sr, y_noise=noise_clip, stationary=False)\n",
    "    \n",
    "    # 保存降噪后音频（WAV格式）\n",
    "    sf.write(DENOISED_PATH, y_denoised, sr, subtype='PCM_16')\n",
    "    print(f\"降噪完成 ({time.time()-t0:.1f}s) → {DENOISED_PATH}\")\n",
    "    \n",
    "    # 更新音频路径为降噪版本，后续步骤使用此文件\n",
    "    AUDIO_PATH = DENOISED_PATH\n",
    "    print(\"✅ 后续转录将使用降噪后音频。\")\n",
    "else:\n",
    "    print(\"⏭️  降噪步骤已跳过，使用原始音频。\")\n"
   ]
  },
  # ── Step 4 ────────────────────────────────────────
  {
   "cell_type": "markdown", "id": "step4", "metadata": {},
   "source": ["## Step 4 - Load Model and Transcribe\n"]
  },
  {
   "cell_type": "code", "execution_count": None, "id": "transcribe", "metadata": {}, "outputs": [],
   "source": [
    "import time\n",
    "from faster_whisper import WhisperModel, BatchedInferencePipeline\n",
    "\n",
    "print(f'Loading model {MODEL_SIZE} ...')\n",
    "t0 = time.time()\n",
    "model = WhisperModel(MODEL_SIZE, device='cuda', compute_type='float16')\n",
    "batched = BatchedInferencePipeline(model=model)\n",
    "print(f'Model loaded in {time.time()-t0:.1f}s')\n",
    "\n",
    "print('Transcribing...')\n",
    "t1 = time.time()\n",
    "segments, info = batched.transcribe(\n",
    "    AUDIO_PATH,\n",
    "    batch_size=BATCH_SIZE,\n",
    "    vad_filter=VAD_FILTER,\n",
    "    word_timestamps=WORD_TIMESTAMPS,\n",
    "    language=LANGUAGE,\n",
    ")\n",
    "segments = list(segments)\n",
    "elapsed = time.time() - t1\n",
    "\n",
    "print(f'Done! {len(segments)} segments in {elapsed:.1f}s')\n",
    "print(f'Language: {info.language} ({info.language_probability:.2%})')\n",
    "print(f'Duration: {info.duration:.1f}s  realtime: {info.duration/elapsed:.1f}x')\n"
   ]
  },
  # ── Step 5 ────────────────────────────────────────
  {
   "cell_type": "markdown", "id": "step5", "metadata": {},
   "source": ["## Step 5 - Save Output\n"]
  },
  {
   "cell_type": "code", "execution_count": None, "id": "save", "metadata": {}, "outputs": [],
   "source": [
    "# Plain text\n",
    "with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:\n",
    "    for seg in segments:\n",
    "        f.write(seg.text.strip() + '\\n')\n",
    "print(f'Text saved: {OUTPUT_PATH}')\n",
    "\n",
    "# SRT subtitle\n",
    "def fmt(sec):\n",
    "    h, r = divmod(int(sec), 3600)\n",
    "    m, s = divmod(r, 60)\n",
    "    return f'{h:02d}:{m:02d}:{s:02d},{int((sec % 1)*1000):03d}'\n",
    "\n",
    "with open(SRT_PATH, 'w', encoding='utf-8') as f:\n",
    "    for i, seg in enumerate(segments, 1):\n",
    "        f.write(f'{i}\\n{fmt(seg.start)} --> {fmt(seg.end)}\\n{seg.text.strip()}\\n\\n')\n",
    "print(f'SRT saved: {SRT_PATH}')\n",
    "\n",
    "print('\\n--- Preview (first 5) ---')\n",
    "for seg in segments[:5]:\n",
    "    print(f'[{seg.start:.1f}s->{seg.end:.1f}s] {seg.text.strip()}')\n"
   ]
  },
  # ── Step 6: WhisperX 说话人分离（必选，咨询优化）─────────
  {
   "cell_type": "markdown", "id": "step6-whisperx-md", "metadata": {},
   "source": [
    "## Step 6 — WhisperX 说话人分离（必选）\n",
    "\n",
    "**咨询场景优化**：\n",
    "- 默认 NUM_SPEAKERS=3（咨询常为 2-3 人）\n",
    "- 提高对齐精度，改善多人交替对话分离\n",
    "- 输出带说话人标注的文本，供 AI 结构化分析\n",
    "\n",
    "**输出文件**：\n",
    "- `transcript_speakers.txt` — 带说话人标注的纯文本\n",
    "- `transcript_speakers.srt` — 带说话人的 SRT 字幕\n"
   ]
  },
  {
   "cell_type": "code", "execution_count": None, "id": "whisperx-diarize", "metadata": {}, "outputs": [],
   "source": [
    "# =========== WhisperX 说话人分离配置 ===========\n",
    "HF_TOKEN     = \"\"   # 在这里填入你的 HuggingFace Access Token\n",
    "NUM_SPEAKERS = 3    # 咨询通常 2-3 人，设为 3 或 None（自动检测）\n",
    "MIN_SPEAKERS = 2    # 最少说话人数\n",
    "MAX_SPEAKERS = 4    # 最多说话人数（咨询不超过 4 人）\n",
    "SPEAKERS_TXT = '/content/drive/MyDrive/transcript_speakers.txt'\n",
    "SPEAKERS_SRT = '/content/drive/MyDrive/transcript_speakers.srt'\n",
    "# ================================================\n",
    "\n",
    "assert HF_TOKEN, \"请填写 HF_TOKEN — 前往 https://huggingface.co/settings/tokens 获取\"\n",
    "\n",
    "print(\"安装 WhisperX...\")\n",
    "import subprocess, time, torch\n",
    "subprocess.run([\"pip\", \"install\", \"-q\", \"whisperx\"], check=True)\n",
    "\n",
    "import whisperx\n",
    "device = \"cuda\" if torch.cuda.is_available() else \"cpu\"\n",
    "\n",
    "# --- 加载音频 ---\n",
    "print(\"加载音频...\")\n",
    "audio = whisperx.load_audio(AUDIO_PATH)\n",
    "\n",
    "# --- 将 faster-whisper segments 转为 WhisperX 格式 ---\n",
    "wx_segments = [\n",
    "    {\n",
    "        \"start\": seg.start,\n",
    "        \"end\":   seg.end,\n",
    "        \"text\":  seg.text.strip(),\n",
    "        \"words\": [\n",
    "            {\"word\": w.word, \"start\": w.start, \"end\": w.end, \"score\": w.probability}\n",
    "            for w in (seg.words or [])\n",
    "        ]\n",
    "    }\n",
    "    for seg in segments\n",
    "]\n",
    "wx_result = {\"segments\": wx_segments, \"language\": LANGUAGE or info.language}\n",
    "\n",
    "# --- 词级对齐（提高分离精度）---\n",
    "print(\"词级对齐...\")\n",
    "t0 = time.time()\n",
    "align_model, align_meta = whisperx.load_align_model(\n",
    "    language_code=wx_result[\"language\"], device=device\n",
    ")\n",
    "wx_result = whisperx.align(\n",
    "    wx_result[\"segments\"], align_model, align_meta, audio, device\n",
    ")\n",
    "print(f\"对齐完成 ({time.time()-t0:.1f}s)\")\n",
    "\n",
    "# --- 说话人分离（咨询优化）---\n",
    "print(\"说话人分离中（咨询场景，约 30-60s）...\")\n",
    "t1 = time.time()\n",
    "diarize_pipeline = whisperx.DiarizationPipeline(\n",
    "    use_auth_token=HF_TOKEN, device=device\n",
    ")\n",
    "diarize_kwargs = {}\n",
    "if NUM_SPEAKERS: diarize_kwargs[\"num_speakers\"] = NUM_SPEAKERS\n",
    "if MIN_SPEAKERS: diarize_kwargs[\"min_speakers\"] = MIN_SPEAKERS\n",
    "if MAX_SPEAKERS: diarize_kwargs[\"max_speakers\"] = MAX_SPEAKERS\n",
    "diarize_segments = diarize_pipeline(audio, **diarize_kwargs)\n",
    "wx_result = whisperx.assign_word_speakers(diarize_segments, wx_result)\n",
    "print(f\"分离完成 ({time.time()-t1:.1f}s)\")\n",
    "\n",
    "# --- 统计说话人 ---\n",
    "speakers_found = sorted(set(\n",
    "    seg.get(\"speaker\", \"UNKNOWN\")\n",
    "    for seg in wx_result[\"segments\"]\n",
    "))\n",
    "print(f\"\\n识别到 {len(speakers_found)} 位说话人: {', '.join(speakers_found)}\")\n",
    "\n",
    "# --- 保存带说话人的纯文本 ---\n",
    "with open(SPEAKERS_TXT, 'w', encoding='utf-8') as f:\n",
    "    current_speaker = None\n",
    "    for seg in wx_result[\"segments\"]:\n",
    "        spk = seg.get(\"speaker\", \"UNKNOWN\")\n",
    "        if spk != current_speaker:\n",
    "            f.write(f\"\\n[{spk}]\\n\")\n",
    "            current_speaker = spk\n",
    "        f.write(seg[\"text\"].strip() + \"\\n\")\n",
    "print(f\"说话人文本已保存: {SPEAKERS_TXT}\")\n",
    "\n",
    "# --- 保存带说话人的 SRT ---\n",
    "def fmt(sec):\n",
    "    h, r = divmod(int(sec), 3600)\n",
    "    m, s = divmod(r, 60)\n",
    "    return f'{h:02d}:{m:02d}:{s:02d},{int((sec % 1)*1000):03d}'\n",
    "\n",
    "with open(SPEAKERS_SRT, 'w', encoding='utf-8') as f:\n",
    "    for i, seg in enumerate(wx_result[\"segments\"], 1):\n",
    "        spk = seg.get('speaker', 'UNKNOWN')\n",
    "        f.write(f\"{i}\\n{fmt(seg['start'])} --> {fmt(seg['end'])}\\n[{spk}] {seg['text'].strip()}\\n\\n\")\n",
    "print(f\"说话人 SRT 已保存: {SPEAKERS_SRT}\")\n",
    "\n",
    "# --- 供后续 AI 优化使用 ---\n",
    "diarized_segments = wx_result[\"segments\"]\n",
    "\n",
    "print(\"\\n--- 预览（前5段）---\")\n",
    "for seg in diarized_segments[:5]:\n",
    "    spk = seg.get('speaker', 'UNKNOWN')\n",
    "    print(f\"[{spk}] [{seg['start']:.1f}s->{seg['end']:.1f}s] {seg['text'].strip()}\")\n"
   ]
  },
  # ── Step 7: AI 优化处理（必选，咨询场景专用）─────────────
  {
   "cell_type": "markdown", "id": "step7-ai-md", "metadata": {},
   "source": [
    "## Step 7 — AI 优化处理（必选）咨询场景强化版\n",
    "\n",
    "**咨询/访谈场景专用优化**：\n",
    "- 提取**用户痛点、产品建议、满意度评分**\n",
    "- 区分**访谈者（研究员） vs 受访者（用户）**\n",
    "- 结构化输出：问题分类、解决方案、待跟进项\n",
    "- 自动总结**关键决策、共识、分歧点**\n",
    "\n",
    "**输出文件**：\n",
    "- `transcript_consultation.md` — 结构化咨询报告（Markdown）\n",
    "- `transcript_summary.txt` — 摘要纯文本\n"
   ]
  },
  {
   "cell_type": "code", "execution_count": None, "id": "ai-optimize", "metadata": {}, "outputs": [],
   "source": [
    "# =========== AI 优化配置（咨询场景） ===========\n",
    "AI_MODEL   = \"deepseek-chat\"  # \"gpt-4o-mini\" / \"deepseek-chat\"\n",
    "AI_API_KEY = \"\"               # 在这里填入你的 API Key\n",
    "MAX_TOKENS = 6000             # 咨询内容较长，增加 token 限额\n",
    "# =============================================\n",
    "\n",
    "assert AI_API_KEY, \"请填写 AI_API_KEY — DeepSeek: https://platform.deepseek.com/  OpenAI: https://platform.openai.com/\"\n",
    "\n",
    "import requests, json, time, os\n",
    "\n",
    "# 优先读取带说话人标注的转录（Step 6 输出），否则回退到原始转录\n",
    "src_path = SPEAKERS_TXT if os.path.exists(SPEAKERS_TXT) else OUTPUT_PATH\n",
    "print(f\"读取源文件: {src_path}\")\n",
    "with open(src_path, 'r', encoding='utf-8') as f:\n",
    "    raw_text = f.read()\n",
    "\n",
    "# 咨询场景专用提示词（含说话人标注）\n",
    "has_speakers = os.path.exists(SPEAKERS_TXT)\n",
    "speaker_prefix = \"（已标注说话人，如 [SPEAKER_00] 为研究员，[SPEAKER_01] 为用户）\" if has_speakers else \"\"\n",
    "\n",
    "prompt = f\"\"\"请将以下用户咨询访谈转录优化为**结构化咨询报告**。\n",
    "\n",
    "【背景】\n",
    "这是关于“乐奇”智能眼镜的用户体验反馈访谈{speaker_prefix}。\n",
    "\n",
    "【优化要求】\n",
    "1. **清理与重组**\n",
    "   - 删除口语重复（对对对、这个这个）\n",
    "   - 补充标点，分段合理\n",
    "   - 合并碎片短句\n",
    "\n",
    "2. **提取核心信息（咨询场景）**\n",
    "   - **用户痛点**：使用中遇到的问题、不便之处\n",
    "   - **产品建议**：用户提出的改进建议、功能需求\n",
    "   - **满意度**：对产品哪些方面满意/不满意\n",
    "   - **使用场景**：用户在什么情境下使用产品\n",
    "\n",
    "3. **结构化输出（Markdown）**\n",
    "   - 按主题分章节（如：佩戴舒适度、视觉体验、软件功能等）\n",
    "   - 用表格或列表整理用户反馈点\n",
    "   - 区分“研究员提问”与“用户回答”（如可能）\n",
    "   - 总结关键发现与行动建议\n",
    "\n",
    "4. **格式要求**\n",
    "   - 使用清晰的小标题（## 一级标题，### 二级标题）\n",
    "   - 关键数据用**粗体**强调\n",
    "   - 列出“待跟进问题”\n",
    "\n",
    "【原始转录开始】\n",
    "{raw_text[:MAX_TOKENS*3]}\n",
    "【原始转录结束】\"\"\"\n",
    "\n",
    "print(\"开始 AI 优化处理（咨询场景）...\")\n",
    "t0 = time.time()\n",
    "result = \"\"\n",
    "\n",
    "if \"deepseek\" in AI_MODEL.lower():\n",
    "    url = \"https://api.deepseek.com/chat/completions\"\n",
    "    headers = {\"Content-Type\": \"application/json\", \"Authorization\": f\"Bearer {AI_API_KEY}\"}\n",
    "    data = {\n",
    "        \"model\": AI_MODEL,\n",
    "        \"messages\": [\n",
    "            {\"role\": \"system\", \"content\": \"你是专业的用户体验研究分析师，擅长从访谈转录中提取结构化洞察，生成清晰、可操作的咨询报告。\"},\n",
    "            {\"role\": \"user\", \"content\": prompt}\n",
    "        ],\n",
    "        \"temperature\": 0.3,\n",
    "        \"max_tokens\": MAX_TOKENS\n",
    "    }\n",
    "    try:\n",
    "        resp = requests.post(url, headers=headers, json=data, timeout=180)\n",
    "        if resp.status_code == 200:\n",
    "            result = resp.json()[\"choices\"][0][\"message\"][\"content\"]\n",
    "        else:\n",
    "            print(f\"DeepSeek API 错误: {resp.status_code} {resp.text[:200]}\")\n",
    "    except Exception as e:\n",
    "        print(f\"请求失败: {e}\")\n",
    "else:\n",
    "    import openai\n",
    "    openai.api_key = AI_API_KEY\n",
    "    try:\n",
    "        resp = openai.ChatCompletion.create(\n",
    "            model=AI_MODEL,\n",
    "            messages=[\n",
    "                {\"role\": \"system\", \"content\": \"你是专业的用户体验研究分析师，擅长从访谈转录中提取结构化洞察，生成清晰、可操作的咨询报告。\"},\n",
    "                {\"role\": \"user\", \"content\": prompt}\n",
    "            ],\n",
    "            temperature=0.3,\n",
    "            max_tokens=MAX_TOKENS\n",
    "        )\n",
    "        result = resp.choices[0].message.content\n",
    "    except Exception as e:\n",
    "        print(f\"OpenAI API 错误: {e}\")\n",
    "\n",
    "if result:\n",
    "    # 咨询场景专用输出文件名\n",
    "    consultation_md  = '/content/drive/MyDrive/transcript_consultation.md'\n",
    "    summary_txt      = '/content/drive/MyDrive/transcript_summary.txt'\n",
    "    with open(consultation_md, 'w', encoding='utf-8') as f:\n",
    "        f.write(result)\n",
    "    with open(summary_txt, 'w', encoding='utf-8') as f:\n",
    "        f.write(result.replace('```markdown', '').replace('```', '').strip())\n",
    "    print(f\"✅ 咨询报告生成完成！（{time.time()-t0:.1f}s）\")\n",
    "    print(f\"   结构化报告 : {consultation_md}\")\n",
    "    print(f\"   摘要文本   : {summary_txt}\")\n",
    "    print(\"\\n--- 报告预览（前 400 字符）---\")\n",
    "    print(result[:400] + \"...\")\n",
    "else:\n",
    "    print(\"⚠️  AI 优化失败，请检查 API Key 或网络。\")\n"
   ]
  },
  # ── Studio Lab 备注 ───────────────────────────────
  {
   "cell_type": "markdown", "id": "studio-lab", "metadata": {},
   "source": [
    "---\n",
    "## Note: Switch to AWS Studio Lab\n",
    "\n",
    "Studio Lab keeps packages persistent. Only change the path:\n",
    "\n",
    "```python\n",
    "AUDIO_PATH = '/home/studio-lab-user/audio.mp3'\n",
    "```\n",
    "\n",
    "Everything else is identical.\n"
   ]
  }
 ]
}

out = '/Users/thursday/WorkBuddy/20260331142519/audio_transcription_faster_whisper.ipynb'
with open(out, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

# validate
with open(out, encoding='utf-8') as f:
    json.load(f)
print('JSON valid ✅')
print('咨询场景优化版 notebook 生成完成！')